/*
1️⃣ Java Basics
Java
Java is a high-level, object-oriented, platform-independent programming language developed by Sun Microsystems (now Oracle) that follows the principle “Write Once, Run Anywhere.”

JVM (Java Virtual Machine)
JVM is an engine that executes Java bytecode, providing platform independence by converting bytecode into machine-specific instructions.

JRE (Java Runtime Environment)
JRE provides the runtime environment required to run Java applications, including JVM and core libraries.

JDK (Java Development Kit)
JDK is a software development kit that includes JRE and development tools like compiler (javac), debugger, and documentation tools.

Bytecode
Bytecode is the intermediate code generated by the Java compiler, which is executed by the JVM.

2️⃣ Data Types & Variables
Data Types
Data types specify the type of data a variable can hold.
Primitive: int, float, double, char, boolean, byte, short, long
Non-Primitive: String, Arrays, Classes, Interfaces

Variable
A variable is a named memory location used to store data.

Type Casting
Type casting is the process of converting one data type into another.

3️⃣ Operators & Control Statements
Operators
Operators are symbols used to perform operations like arithmetic, logical, relational, etc.

Control Statements
Control the flow of execution of a program.
Conditional: if, else, switch
Looping: for, while, do-while
Jumping: break, continue, return

4️⃣ Object-Oriented Programming (OOPS)
Class
A class is a blueprint that defines properties and behaviors of objects.

Object
An object is an instance of a class representing a real-world entity.

Encapsulation
Encapsulation is the process of wrapping data and methods together and restricting direct access using access modifiers.

Inheritance
Inheritance allows a class to acquire properties and methods of another class using extends.

Polymorphism
Polymorphism allows one method to perform different behaviors.
Compile-time (Method Overloading)
Runtime (Method Overriding)

Abstraction
Abstraction hides implementation details and shows only essential features.

Interface
An interface is a contract that contains abstract methods (and default/static methods from Java 8).

Abstract Class
A class that cannot be instantiated and may contain abstract and non-abstract methods.

5️⃣ Constructors & Keywords
Constructor
A constructor is a special method used to initialize objects.

this Keyword
Refers to the current object.

super Keyword
Refers to the parent class object or constructor.

static Keyword
Used for class-level members shared across all objects.

final Keyword
Used to restrict modification:
Final variable → constant
Final method → cannot override
Final class → cannot inherit

6️⃣ Exception Handling
Exception
An exception is an unexpected event that disrupts program flow.

Checked Exception
Checked at compile-time (e.g., IOException).

Unchecked Exception
Occurs at runtime (e.g., NullPointerException).

try-catch-finally
Used to handle exceptions gracefully.

throw / throws
Used to explicitly throw or declare exceptions.

7️⃣ Packages & Access Modifiers
Package
A package is a namespace that groups related classes and interfaces.

Access Modifiers
Control the visibility of classes and members
private
default
protected
public

8️⃣ Strings & Arrays
String
String is an immutable sequence of characters.

StringBuffer
Mutable and thread-safe string.

StringBuilder
Mutable and non-thread-safe, faster than StringBuffer.

Array
An array is a fixed-size data structure that stores elements of the same type.

9️⃣ Collections Framework
Collection Framework
A unified architecture for storing and manipulating groups of objects.

List
Allows duplicate elements and maintains insertion order.
ArrayList
LinkedList
Vector
Set
Does not allow duplicates.
HashSet
LinkedHashSet
TreeSet
Map
Stores data in key-value pairs.
HashMap
LinkedHashMap
TreeMap
Hashtable

🔟 Multithreading & Concurrency
Thread
A thread is a lightweight process for executing tasks concurrently.

Multithreading
Executing multiple threads simultaneously to improve performance.

Synchronization
Controls access to shared resources in multithreaded environments.

Deadlock
A situation where two or more threads wait indefinitely for each other.

1️⃣1️⃣ Java 8+ Features
Lambda Expression
Provides a functional programming approach using anonymous functions.

Functional Interface
An interface with exactly one abstract method.

Stream API
Used to process collections in a functional manner.

Optional
A container object used to avoid NullPointerException.

1️⃣2️⃣ File Handling & I/O
File Handling
Used to read and write data to files.

Serialization
Converting an object into a byte stream.

Deserialization
Reconstructing an object from a byte stream.

1️⃣3️⃣ JDBC
JDBC
Java Database Connectivity is an API to connect and execute queries on databases.

DriverManager
Manages database drivers.

PreparedStatement
Used for precompiled SQL queries and improves performance and security.

1️⃣4️⃣ Design Patterns (Basics)
Singleton
Ensures only one instance of a class exists.

Factory Pattern
Creates objects without exposing instantiation logic.

DAO Pattern
Separates data access logic from business logic.

1️⃣5️⃣ Java Frameworks
Spring Framework
A lightweight framework for enterprise application development.

Spring Boot
Simplifies Spring applications with auto-configuration.

Hibernate
An ORM (Object Relational Mapping) framework that maps Java objects to database tables.

JPA
Java Persistence API for object-relational persistence.

REST API
An architectural style for stateless web services.

1️⃣6️⃣ Build & Tools
Maven
A build automation tool for dependency management.

Gradle
A modern build tool focused on performance and flexibility.

JUnit
A unit testing framework for Java.
*/